### ISSUE TITLE
Implement Layout for app

### ISSUE THREAD

**Issue by mehdi-torabiv** [TogetherCrew/identity-on-chain-platform#26]
```[tasklist]
### Tasks
- [ ] https://github.com/TogetherCrew/identity-on-chain-platform/issues/33
- [ ] https://github.com/TogetherCrew/identity-on-chain-platform/issues/30
- [ ] https://github.com/TogetherCrew/identity-on-chain-platform/issues/32
- [ ] Button Component
- [ ] https://github.com/TogetherCrew/identity-on-chain-platform/issues/35
- [ ] https://github.com/TogetherCrew/identity-on-chain-platform/issues/39
```
